server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false








welcome:
  message: I am eureka service