server:
  port: 2220

spring:
  application:
    name: proxy-service

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

zuul:
  prefix: /api
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  routes:
    front:
      path: /front-svc/**
      serviceId: front-service
    test:
      path: /test-svc/**
      serviceId: front-service
      
management:
  security:
    enabled: false

logging:
  level:
    root: INFO

---
spring:
  profiles: gae
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service-dot-nklee-project.appspot.com/eureka/