server:
  port: 3333

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

welcome:
  message: welcome order service!!

---
spring:
  profiles: gae
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service-dot-nklee-project.appspot.com/eureka/