server:
  port: 2222

spring:
   mvc:
      view:
         suffix: .jsp
         prefix: /WEB-INF/jsp/
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      view-names: thymeleaf/*

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

# 리프래시를 위해 추가
management:
  endpoints:
    web:
      exposure:
        include: "refresh"
---
spring:
  profiles: gae
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service-dot-nklee-project.appspot.com/eureka/

---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service-dot-nklee-project.appspot.com/eureka/