server:
  port: ${PORT:2222}


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.20.12.23:9999/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

welcome:
  message: welcome front service!!