server:
  port: ${PORT:9999}

eureka:
  instance:
    prefer-ip-address: true
  server:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  datacenter: mycenter
  environment: test




welcome:
  message: I am eureka service