service: proxy-service
runtime: java
env: flex

health_check:
  enable_health_check: False

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1.0

env_variables:
  SPRING_PROFILES_ACTIVE: 'gae'