server:
  port: 18888

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
      config:
        server:
          native:
            searchLocations: classpath:/configs

---
spring:
  profiles: gae
server:
  port: 8080